# -*- coding: utf-8 -*-
"""dlproj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sxK8ifofRDBS4IFUAnKzO1CDDhEGv-mH
"""

from google.colab import files
files.upload()  # upload kaggle.json

!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets download -d ioanagheorghiu/historical-flight-and-weather-data
!unzip historical-flight-and-weather-data.zip -d flight_weather_data

import pandas as pd
import glob

# read all monthly csv files
path = "flight_weather_data/"
all_files = glob.glob(path + "*.csv")

dfs = [pd.read_csv(f) for f in all_files]
df = pd.concat(dfs, ignore_index=True)
print("Total records:", len(df))
df.head()
df.info()
df.describe(include='all')

df.columns
df.isna().sum().sort_values(ascending=False).head(20)

# Drop high-missing and non-useful columns
drop_cols = ['actual_arrival_dt', 'actual_departure_dt', 'tail_number']
df = df.drop(columns=[c for c in drop_cols if c in df.columns])

# Fill missing weather columns with median
weather_cols = [c for c in df.columns if 'Hourly' in c or 'Precipitation' in c]
for c in weather_cols:
    df[c] = df[c].fillna(df[c].median())

# Quick check
df.isna().sum().sort_values(ascending=False).head(10)

[dfc for dfc in df.columns if 'delay' in dfc.lower()]

# Flights delayed more than 15 minutes are considered 'Delayed'
df['DELAYED'] = (df['arrival_delay'] > 15).astype(int)

# Quick check
df['DELAYED'].value_counts(normalize=True)

num_cols = [
    'departure_delay',
    'delay_carrier',
    'delay_weather',
    'delay_national_aviation_system',
    'delay_security',
    'delay_late_aircarft_arrival',
    'HourlyDryBulbTemperature_x',
    'HourlyVisibility_x',
    'HourlyWindSpeed_x',
    'HourlyPrecipitation_x',
    'HourlyDryBulbTemperature_y',
    'HourlyVisibility_y',
    'HourlyWindSpeed_y',
    'HourlyPrecipitation_y',
    'weekday'
]

cat_cols = ['carrier_code', 'origin_airport', 'destination_airport']
target = 'DELAYED'

# Filter dataset
df_model = df[num_cols + cat_cols + [target]].dropna()
print(df_model.shape)
df_model.head()

from sklearn.preprocessing import LabelEncoder, StandardScaler

# Label encode categorical columns
for c in cat_cols:
    le = LabelEncoder()
    df_model[c] = le.fit_transform(df_model[c].astype(str))

# Scale numeric columns
scaler = StandardScaler()
df_model[num_cols] = scaler.fit_transform(df_model[num_cols])
df_sample = df_model.sample(n=80000, random_state=42)  # you can go up to 100k if Colab has GPU
print(df_sample.shape)

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Redefine
num_cols = [
    'departure_delay','delay_carrier','delay_weather','delay_national_aviation_system',
    'delay_security','delay_late_aircarft_arrival',
    'HourlyDryBulbTemperature_x','HourlyVisibility_x','HourlyWindSpeed_x','HourlyPrecipitation_x',
    'HourlyDryBulbTemperature_y','HourlyVisibility_y','HourlyWindSpeed_y','HourlyPrecipitation_y','weekday'
]
cat_cols = ['carrier_code','origin_airport','destination_airport']
target = 'DELAYED'

X = df_sample[num_cols + cat_cols]
y = df_sample[target].values

# Label encode categorical again (since we took a subset)
for c in cat_cols:
    le = LabelEncoder()
    X[c] = le.fit_transform(X[c].astype(str))

# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=42)
T = 5  # sequence length
num_data = X_train[num_cols].values
cat_data = X_train[cat_cols].values

X_seq, X_static, Y = [], [], []
for i in range(T, len(num_data)):
    X_seq.append(num_data[i-T:i])
    X_static.append(cat_data[i])
    Y.append(y_train[i])

X_seq = np.array(X_seq)
X_static = np.array(X_static)
Y = np.array(Y)

print("LSTM input shape:", X_seq.shape)
print("Static input shape:", X_static.shape)

import tensorflow as tf
from tensorflow.keras import layers, Model, Input
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# ------------------------------------------------------------
# 1️⃣ DEFINE FOCAL LOSS HERE (before building the model)
# ------------------------------------------------------------
from tensorflow.keras import backend as K

def focal_loss(gamma=2., alpha=.25):
    def focal_loss_fixed(y_true, y_pred):
        y_true = tf.cast(y_true, tf.float32)
        y_pred = tf.clip_by_value(y_pred, K.epsilon(), 1 - K.epsilon())
        cross_entropy = -y_true * tf.math.log(y_pred) - (1 - y_true) * tf.math.log(1 - y_pred)
        weight = alpha * y_true * tf.pow(1 - y_pred, gamma) + (1 - alpha) * (1 - y_true) * tf.pow(y_pred, gamma)
        return tf.reduce_mean(weight * cross_entropy)
    return focal_loss_fixed


# ------------------------------------------------------------
# 2️⃣ DEFINE MODEL
# ------------------------------------------------------------
T, n_features = X_seq.shape[1], X_seq.shape[2]
n_static = X_static.shape[1]

seq_input = Input(shape=(T, n_features))
x = layers.LSTM(128, return_sequences=True, dropout=0.3, recurrent_dropout=0.3)(seq_input)
x = layers.LSTM(64, dropout=0.3, recurrent_dropout=0.3)(x)
x = layers.BatchNormalization()(x)

static_input = Input(shape=(n_static,))
s = layers.Dense(64, activation='relu', kernel_regularizer=tf.keras.regularizers.l2(1e-4))(static_input)
s = layers.BatchNormalization()(s)
s = layers.Dropout(0.3)(s)

combined = layers.concatenate([x, s])
z = layers.Dense(128, activation='relu')(combined)
z = layers.BatchNormalization()(z)
z = layers.Dropout(0.4)(z)
output = layers.Dense(1, activation='sigmoid')(z)

optimizer = tf.keras.optimizers.Adam(learning_rate=0.0005)
model = Model(inputs=[seq_input, static_input], outputs=output)

# ------------------------------------------------------------
# 3️⃣ USE FOCAL LOSS INSTEAD OF BINARY CROSSENTROPY
# ------------------------------------------------------------
model.compile(
    optimizer=optimizer,
    loss=focal_loss(gamma=2., alpha=0.25),
    metrics=['accuracy', tf.keras.metrics.AUC()]
)

model.summary()

# ------------------------------------------------------------
# 4️⃣ CALLBACKS AND CLASS WEIGHTS
# ------------------------------------------------------------
callbacks = [
    tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True),
    tf.keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, min_lr=1e-6, verbose=1)
]

from sklearn.model_selection import train_test_split
from sklearn.utils import class_weight

# Train–validation split
X_seq_train, X_seq_val, X_static_train, X_static_val, Y_train, Y_val = train_test_split(
    X_seq, X_static, Y, test_size=0.2, random_state=42, stratify=Y
)

# Compute class weights
class_weights = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(Y_train),
    y=Y_train
)
class_weights = dict(enumerate(class_weights))
print("Class Weights:", class_weights)

# Train
history = model.fit(
    [X_seq_train, X_static_train], Y_train,
    validation_data=([X_seq_val, X_static_val], Y_val),
    epochs=30,
    batch_size=256,
    callbacks=callbacks,
    verbose=1,
    class_weight=class_weights
)

# Evaluate using validation data for threshold
from sklearn.metrics import roc_curve

y_val_prob = model.predict([X_seq_val, X_static_val]).ravel()
fpr, tpr, thresholds = roc_curve(Y_val, y_val_prob)
best_idx = np.argmax(tpr - fpr)
best_threshold = thresholds[best_idx]
print("\nBest Threshold Found:", best_threshold)

# Apply new threshold on full data
y_pred_prob_all = model.predict([X_seq, X_static]).ravel()
y_pred_opt = (y_pred_prob_all > best_threshold).astype(int)

print("\nClassification Report (Optimized Threshold):\n", classification_report(Y, y_pred_opt))
print("ROC AUC (Optimized):", roc_auc_score(Y, y_pred_prob_all))

# Confusion Matrix
plt.figure(figsize=(5,4))
sns.heatmap(confusion_matrix(Y, y_pred_opt), annot=True, fmt='d', cmap='Greens')
plt.title("Confusion Matrix - Optimized Threshold")
plt.show()

# Plot training history
plt.figure(figsize=(6,4))
plt.plot(history.history['accuracy'], label='Train Acc')
plt.plot(history.history['val_accuracy'], label='Val Acc')
plt.legend()
plt.title("Training vs Validation Accuracy")
plt.show()

# -------------------------------
# 🔹 FLIGHT DELAY PREDICTION DEMO
# -------------------------------
import pandas as pd
import numpy as np

# Select a few random test samples
num_samples = 5
sample_idx = np.random.choice(len(X_seq), num_samples, replace=False)

sample_seq = X_seq[sample_idx]
sample_static = X_static[sample_idx]
sample_labels = Y[sample_idx]

# Predict probabilities
sample_probs = model.predict([sample_seq, sample_static]).ravel()

# Show results
print("\n🔹 Sample Flight Predictions:\n")
for i in range(num_samples):
    prob = sample_probs[i]
    true = "DELAYED" if sample_labels[i] == 1 else "ON TIME"
    pred = "LIKELY DELAYED" if prob > 0.5 else "LIKELY ON TIME"
    print(f"✈️  Flight {i+1}")
    print(f"True Status     : {true}")
    print(f"Predicted Status: {pred}")
    print(f"Delay Probability: {prob:.3f}\n")

import numpy as np

def predict_flight_delay():
    print("\n✈️ Enter Flight Details Below:\n")

    # --- Example user inputs ---
    departure_delay = float(input("Departure delay (minutes): "))
    delay_carrier = float(input("Carrier delay (minutes): "))
    delay_weather = float(input("Weather delay (minutes): "))
    delay_nas = float(input("National aviation system delay (minutes): "))
    delay_security = float(input("Security delay (minutes): "))
    delay_late_aircraft = float(input("Late aircraft delay (minutes): "))

    HourlyDryBulbTemperature_x = float(input("Origin temperature (°C): "))
    HourlyVisibility_x = float(input("Origin visibility (km): "))
    HourlyWindSpeed_x = float(input("Origin wind speed (km/h): "))
    HourlyPrecipitation_x = float(input("Origin precipitation (mm): "))

    HourlyDryBulbTemperature_y = float(input("Destination temperature (°C): "))
    HourlyVisibility_y = float(input("Destination visibility (km): "))
    HourlyWindSpeed_y = float(input("Destination wind speed (km/h): "))
    HourlyPrecipitation_y = float(input("Destination precipitation (mm): "))
    weekday = int(input("Day of week (0=Mon, 6=Sun): "))

    # --- Static categorical ---
    carrier_code = input("Carrier code (e.g. AA, DL, UA): ")
    origin_airport = input("Origin airport (e.g. ATL, LAX): ")
    destination_airport = input("Destination airport (e.g. JFK, ORD): ")

    # --- Preprocessing same as training ---
    num_features = np.array([
        departure_delay, delay_carrier, delay_weather, delay_nas,
        delay_security, delay_late_aircraft,
        HourlyDryBulbTemperature_x, HourlyVisibility_x, HourlyWindSpeed_x, HourlyPrecipitation_x,
        HourlyDryBulbTemperature_y, HourlyVisibility_y, HourlyWindSpeed_y, HourlyPrecipitation_y,
        weekday
    ]).reshape(1, -1)

    # Repeat same values T times for LSTM input shape
    X_seq_input = np.repeat(num_features[:, np.newaxis, :], T, axis=1)

    # Encode categorical (make sure same label encoders are saved)
    cat_features = np.array([[0, 0, 0]])  # dummy if you didn't save encoders

    # --- Predict ---
    pred_prob = model.predict([X_seq_input, cat_features]).ravel()[0]
    pred_class = "LIKELY DELAYED" if pred_prob > 0.5 else "LIKELY ON TIME"

    print("\n🧾 Prediction Result:")
    print(f"Delay Probability: {pred_prob:.3f}")
    print(f"Predicted Status : {pred_class}")

# Run it
predict_flight_delay()